### ISSUE TITLE
error on empty file

### ISSUE THREAD

**Issue by da0ka** [eyaler/ztml#1]
console reports ValueError: max() arg is an empty sequence

**Comment by eyaler** [comment]
Good catch! I added a default for the offending max() in the Huffman encoder, pushed to https://github.com/eyaler/ztml/commit/f4ef8065ecee815c90c2d7ed5fa8c6542aac5420. However, please note that an empty file will explicitly fail later here: https://github.com/eyaler/ztml/blob/main/ztml/deflate.py#L82
While I would have liked to allow an empty file to complete successfully, as an edge test case and for computing overheads, it seems that the PNG encoder does not support an empty image, so I just added an assertion.
Please lmk if you have a different suggestion or use case.
