### ISSUE TITLE
Playing on web browser

### ISSUE THREAD

**Issue by da0ka** [eyaler/ztml#2]
I want to play ztml on web browser. Could you write JavaScript version? [i2sr.js](https://github.com/da0ka/bsc-m03js/blob/main/i2sr.js) and [libsais.js](https://github.com/da0ka/bsc-m03js/blob/main/libsais.js) are useful for BWT.

**Comment by eyaler** [comment]
Thanks. While both making this into a JS library, and providing a web interface are in the [TODO](https://github.com/eyaler/ztml/blob/main/TODO.md), I do not plan to do this in the near future. I do provide a [Colab](https://github.com/eyaler/ztml/blob/main/ZTML.ipynb), and of course PR's are welcome!
