### ISSUE TITLE
Feat.req. Win build

### ISSUE THREAD

**Issue by necros2k7** [eyaler/ztml#3]
subj

**Comment by eyaler** [comment]
@necros2k7 This is Python code which works on Windows. Do you mean you would prefer a stand-alone executable?

**Comment by necros2k7** [comment]
Yes, stand-alone executable

**Comment by eyaler** [comment]
Got it. I added the feature request to the [TODO](https://github.com/eyaler/ztml/blob/main/TODO.md). I am not sure how difficult it is to do this allowing for the optional use of the external ECT executable, and the webdrivers used in validation. Also, it would be nice to have Linux and Mac versions. Anyway, this is low priority for me to do myself, but I would happily consider a PR which includes code to generate such executable(s).
