### ISSUE TITLE
bug in --raw

### ISSUE THREAD

**Issue by da0ka** [eyaler/ztml#5]
I tested `--raw` option. if source code uses variable `D`(like`<script>D=0</script>`) then console reports `D.close is not a function`

**Comment by da0ka** [comment]
`with(D)write(t),close()` or `D.close(D.write(t))` gives no error

**Comment by eyaler** [comment]
@da0ka thanks! good catch. i don't want to use with() because it is deprecated, but second options does the job + saves 1 char!

**Comment by eyaler** [comment]
closed by b90d6b1
