### ISSUE TITLE
reduce decoder size

### ISSUE THREAD

**Issue by da0ka** [eyaler/ztml#6]
current:
`for(j=t='';j<b.length;t+=s[K(d[k*2-1])+m])for(k=c='0b0';(m=2**k-K(d[k++*2])-c)<0;)c+=b[j++]`
suggestion:
`for(j=t='';j<b.length;t+=s[K(d[k*2-1])+m-c])for(k=c=0;(m=2**k-K(d[k++*2]))<c;)c+=c+b[j++]`

**Comment by eyaler** [comment]
@da0ka very nice trick! however we do not need to change the "-c" location, right?

can be:
` for(j=t='';j<b.length;t+=s[K(d[k*2-1])+m])for(k=c=0;(m=2**k-K(d[k++*2])-c)<0;)c+=c+b[j++]`

**Comment by eyaler** [comment]
closed by b90d6b1
