### ISSUE TITLE
decoder optimization

### ISSUE THREAD

**Issue by da0ka** [eyaler/ztml#7]
I tested several times, and works well.

deflate.py:
line 176
`j={bit_len}` to `j=l={bit_len}`
line 179
`{bitarray_var}={bitarray_var}.slice(0,{bit_len})` to `{bitarray_var}.length=l={bit_len}`

huffman.py:line 82
`j<{bitarray_var}.length` to `j<l`

**Comment by eyaler** [comment]
Thanks @da0ka !
I want to keep the modules somewhat independent from each other, if the cost is just two chars.
As regard to setting the length of an array instead of slice, I did not know about this trick! will adopt. it's too bad it does not work for strings as well.

**Comment by eyaler** [comment]
closed via 7b010b2
